### ISSUE TITLE
--service option failing when using log analyze

### ISSUE THREAD

**Issue by alexandreleroux** [geopython/GeoUsage#3]
I followed the installation instructions and got a few warnings while doing so, but not errors.

Afterwards, running `GeoUsage --help` and `GeoUsage --version` work as expected, but running `GeoUsage log analyze --service=OGC:WMS --logfile MyLogFile` outputs this error: `Error: no such option: --service`.

Please advise. Want me to provide the installation log to help access? Thanks!

**Comment by tomkralidis** [comment]
Fixed in master.  Note that the flag is now `--service-type`.  Can you try again?  Note that WMS is our only currently supported OWS (more to come).

**Comment by alexandreleroux** [comment]
Confirmed working, thanks. Closing ticket.
